Allow more shaped recipe sizes
xenondevs/Nova pull request #219
Opened 2022-12-25 05:13 UTC by MelnCat

Currently, Nova only supports 3x3 shaped recipes. However, vanilla and bukkit actually supports many other shapes natively, such as 2x3, 3x2, 3x1, 1x3, etc. This pull request allows Nova to take advantage of the native recipe sizes, and allows other shaped recipe sizes to be used.

2022-12-25 10:53 UTC, NichtStudioCode requested changes
You're not using our [codestyle](https://github.com/xenondevs/Nova/blob/main/codestyle.xml).
You just copied decompiled Minecraft code, which is (due to being decompiled code) very hard to read and overly complex.

2022-12-25 10:53 UTC, NichtStudioCode commented on nova/src/main/kotlin/xyz/xenondevs/nova/data/recipe/NovaCraftingRecipes.kt
> +    private fun matches(inventorycrafting: CraftingContainer, i: Int, j: Int, inverted: Boolean): Boolean {
Did you just copy the decompiled code from ShapedRecipe?

2022-12-25 10:53 UTC, NichtStudioCode commented on nova/src/main/kotlin/xyz/xenondevs/nova/data/recipe/NovaCraftingRecipes.kt
> +        for (i in 0..inventorycrafting.width - width) {
Please give your variables meaningful names

2022-12-25 10:53 UTC, NichtStudioCode commented on nova/src/main/kotlin/xyz/xenondevs/nova/data/recipe/NovaCraftingRecipes.kt
> +                    recipeitemstack = if (inverted)
The inverted parameter is always true

2022-12-25 20:08 UTC, MelnCat commented
Code has been refactored and reriiten

2022-12-26 17:10 UTC, NichtStudioCode approved these changes

2022-12-26 17:11 UTC, merged